"""
agents/mock_data.py — hardcoded fallback products.

Used when all live API tiers fail. Never raises exceptions.
Covers the most common Indian e-commerce search categories.
"""

MOCK_PRODUCTS: dict[str, list[dict]] = {
    "laptop": [
        {
            "title": "Acer Aspire Lite (Intel Core i3-1215U, 8GB RAM, 512GB SSD)",
            "price": 28990.0,
            "rating": 4.1,
            "review_count": 1247,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/B0CABC001",
        },
        {
            "title": "Lenovo IdeaPad Gaming 3 (i5-12450H, 16GB, RTX 3050)",
            "price": 67990.0,
            "rating": 4.1,
            "review_count": 1923,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/lenovo-ideapad-gaming",
        },
        {
            "title": "HP Victus 15 (Ryzen 5 5600H, 8GB, GTX 1650)",
            "price": 59999.0,
            "rating": 4.2,
            "review_count": 3102,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/B09ABC003",
        },
        {
            "title": "Acer Nitro 5 (i5-12500H, 8GB, RTX 3050Ti)",
            "price": 72990.0,
            "rating": 4.0,
            "review_count": 1450,
            "source": "Croma",
            "link": "https://www.croma.com/acer-nitro-5",
        },
        {
            "title": "MSI GF63 Thin (i7-12650H, 16GB, RTX 4050)",
            "price": 79990.0,
            "rating": 4.4,
            "review_count": 890,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/B09ABC005",
        },
    ],
    "phone": [
        # ── OnePlus 12 (flagship) — multiple sources ──────────────────────────
        {
            "title": "OnePlus 12 5G (12GB/256GB, Snapdragon 8 Gen 3, Hasselblad Camera)",
            "price": 64999.0,
            "rating": 4.6,
            "review_count": 4200,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/B0CRN4B8K6",
        },
        {
            "title": "OnePlus 12 5G (12GB/256GB, Snapdragon 8 Gen 3, 100W SuperVOOC)",
            "price": 62999.0,
            "rating": 4.5,
            "review_count": 3800,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/oneplus-12-5g",
        },
        {
            "title": "OnePlus 12 5G 256GB Silky Black (Snapdragon 8 Gen 3)",
            "price": 63999.0,
            "rating": 4.5,
            "review_count": 1900,
            "source": "Reliance Digital",
            "link": "https://www.reliancedigital.in/oneplus-12",
        },
        {
            "title": "OnePlus 12 5G (16GB/512GB, Snapdragon 8 Gen 3) — Top Tier",
            "price": 72999.0,
            "rating": 4.7,
            "review_count": 1100,
            "source": "OnePlus Store",
            "link": "https://www.oneplus.in/12",
        },
        {
            "title": "OnePlus 12 5G (12GB/256GB) Flowy Emerald",
            "price": 64499.0,
            "rating": 4.4,
            "review_count": 980,
            "source": "Croma",
            "link": "https://www.croma.com/oneplus-12",
        },
        # ── OnePlus 12R (value flagship) — multiple sources ───────────────────
        {
            "title": "OnePlus 12R 5G (8GB/128GB, Snapdragon 8 Gen 1, 80W SuperVOOC)",
            "price": 39999.0,
            "rating": 4.4,
            "review_count": 5600,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/B0CQDM4W3Q",
        },
        {
            "title": "OnePlus 12R 5G (8GB/256GB, Snapdragon 8 Gen 1) Cool Blue",
            "price": 42999.0,
            "rating": 4.4,
            "review_count": 4900,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/oneplus-12r-5g",
        },
        {
            "title": "OnePlus 12R 5G 256GB Iron Gray (Snapdragon 8 Gen 1)",
            "price": 41999.0,
            "rating": 4.3,
            "review_count": 2100,
            "source": "Reliance Digital",
            "link": "https://www.reliancedigital.in/oneplus-12r",
        },
        {
            "title": "OnePlus 12R 5G (16GB/256GB, Snapdragon 8 Gen 1) — Pro",
            "price": 44999.0,
            "rating": 4.5,
            "review_count": 1400,
            "source": "OnePlus Store",
            "link": "https://www.oneplus.in/12r",
        },
        {
            "title": "OnePlus 12R 5G (8GB/128GB) Cool Blue — Value Pick",
            "price": 38999.0,
            "rating": 4.3,
            "review_count": 1800,
            "source": "Croma",
            "link": "https://www.croma.com/oneplus-12r",
        },
        # ── Other phones ──────────────────────────────────────────────────────
        {
            "title": "Samsung Galaxy M34 5G (8GB/128GB, Exynos 1280)",
            "price": 16999.0,
            "rating": 4.2,
            "review_count": 12450,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/B0C001",
        },
        {
            "title": "Redmi Note 13 Pro 5G (8GB/256GB, Snapdragon 7s Gen 2)",
            "price": 24999.0,
            "rating": 4.3,
            "review_count": 8920,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/redmi-note-13-pro",
        },
        {
            "title": "iQOO Z9 5G (12GB/256GB, Dimensity 7200)",
            "price": 22999.0,
            "rating": 4.4,
            "review_count": 3780,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/iqoo-z9",
        },
    ],
    "tv": [
        {
            "title": "Samsung 43-inch 4K Smart TV (Crystal UHD, Tizen OS)",
            "price": 34990.0,
            "rating": 4.3,
            "review_count": 5620,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/TV001",
        },
        {
            "title": "LG 43-inch 4K NanoCell TV (a5 Gen6 Processor)",
            "price": 42990.0,
            "rating": 4.4,
            "review_count": 2340,
            "source": "Croma",
            "link": "https://www.croma.com/lg-nanocell",
        },
        {
            "title": "Sony Bravia 43 X74L 4K Google TV",
            "price": 52990.0,
            "rating": 4.5,
            "review_count": 1890,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/TV003",
        },
        {
            "title": "MI TV 5X 43-inch 4K QLED (PatchWall, Android TV)",
            "price": 29999.0,
            "rating": 4.1,
            "review_count": 7230,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/mi-tv-5x",
        },
        {
            "title": "Hisense 43A6H 4K UHD Smart TV (VIDAA OS)",
            "price": 27990.0,
            "rating": 4.0,
            "review_count": 1120,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/TV005",
        },
    ],
    "headphones": [
        {
            "title": "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
            "price": 24990.0,
            "rating": 4.6,
            "review_count": 18920,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/HP001",
        },
        {
            "title": "Boat Rockerz 450 Bluetooth On-Ear Headphones",
            "price": 1499.0,
            "rating": 4.0,
            "review_count": 45200,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/HP002",
        },
        {
            "title": "JBL Tune 770NC Wireless Noise Cancelling Headphones",
            "price": 6999.0,
            "rating": 4.2,
            "review_count": 3450,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/jbl-tune-770nc",
        },
        {
            "title": "Jabra Evolve2 55 Business Wireless Headset",
            "price": 18999.0,
            "rating": 4.4,
            "review_count": 780,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/HP004",
        },
        {
            "title": "Bose QuietComfort 45 Wireless Noise Cancelling Headphones",
            "price": 29900.0,
            "rating": 4.5,
            "review_count": 4120,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/HP005",
        },
    ],
    "earbuds": [
        {
            "title": "boAt Airdopes 141 TWS Earbuds (42H Playtime, ENx Tech)",
            "price": 1299.0,
            "rating": 4.1,
            "review_count": 45000,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/EB001",
        },
        {
            "title": "realme Buds Air 5 TWS Earbuds (50dB ANC, 38H Playtime)",
            "price": 3999.0,
            "rating": 4.2,
            "review_count": 12000,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/realme-buds-air-5",
        },
        {
            "title": "Samsung Galaxy Buds FE True Wireless Earbuds (ANC, Comfort Fit)",
            "price": 5999.0,
            "rating": 4.3,
            "review_count": 8500,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/EB003",
        },
        {
            "title": "Sony WF-C700N TWS Earbuds (Noise Cancelling, 15H Battery)",
            "price": 7990.0,
            "rating": 4.4,
            "review_count": 3200,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/EB004",
        },
    ],
    "tablet": [
        {
            "title": "Samsung Galaxy Tab A9+ (8GB/128GB, Wi-Fi, 11-inch)",
            "price": 23999.0,
            "rating": 4.3,
            "review_count": 4200,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/TAB001",
        },
        {
            "title": "Redmi Pad SE (8GB/256GB, Snapdragon 680, 11-inch)",
            "price": 17999.0,
            "rating": 4.1,
            "review_count": 3100,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/redmi-pad-se",
        },
        {
            "title": "Realme Pad 2 (6GB/128GB, Unisoc T616, 11.5-inch)",
            "price": 14999.0,
            "rating": 4.0,
            "review_count": 2200,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/TAB003",
        },
        {
            "title": "Apple iPad (10th Gen, 64GB, Wi-Fi)",
            "price": 49900.0,
            "rating": 4.7,
            "review_count": 9800,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/TAB004",
        },
    ],
    "speaker": [
        {
            "title": "JBL Charge 5 Portable Bluetooth Speaker",
            "price": 14999.0,
            "rating": 4.6,
            "review_count": 8900,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/SPK001",
        },
        {
            "title": "Boat Stone 1200 14W Bluetooth Speaker",
            "price": 2499.0,
            "rating": 4.1,
            "review_count": 12400,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/boat-stone-1200",
        },
        {
            "title": "Sony SRS-XB33 Extra Bass Bluetooth Speaker",
            "price": 9999.0,
            "rating": 4.4,
            "review_count": 5600,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/SPK003",
        },
        {
            "title": "Bose SoundLink Flex Bluetooth Portable Speaker",
            "price": 11900.0,
            "rating": 4.5,
            "review_count": 3200,
            "source": "Croma",
            "link": "https://www.croma.com/bose-soundlink-flex",
        },
    ],
    "camera": [
        {
            "title": "Canon EOS 1500D DSLR (18-55mm Lens, 24.1 MP)",
            "price": 34995.0,
            "rating": 4.4,
            "review_count": 7800,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/CAM001",
        },
        {
            "title": "Sony Alpha ZV-E10 Mirrorless Camera (16-50mm Lens)",
            "price": 62990.0,
            "rating": 4.5,
            "review_count": 2900,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/CAM002",
        },
        {
            "title": "GoPro Hero 12 Black Action Camera",
            "price": 39999.0,
            "rating": 4.3,
            "review_count": 4100,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/gopro-hero12",
        },
        {
            "title": "Logitech C920 HD Pro Webcam (1080p/30fps)",
            "price": 7495.0,
            "rating": 4.3,
            "review_count": 6300,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/CAM004",
        },
    ],
    "watch": [
        {
            "title": "Samsung Galaxy Watch 6 Classic (47mm, Bluetooth)",
            "price": 34999.0,
            "rating": 4.4,
            "review_count": 3600,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/WCH001",
        },
        {
            "title": "Noise ColorFit Ultra 3 Smartwatch (AMOLED, Bluetooth Calling)",
            "price": 2999.0,
            "rating": 4.1,
            "review_count": 15000,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/noise-colorfit-ultra3",
        },
        {
            "title": "Amazfit GTS 4 Mini Smartwatch (GPS, SpO2, 70 Sports Modes)",
            "price": 6999.0,
            "rating": 4.2,
            "review_count": 5400,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/WCH003",
        },
        {
            "title": "Mi Band 8 Pro Fitness Tracker (AMOLED, Heart Rate)",
            "price": 4999.0,
            "rating": 4.3,
            "review_count": 8200,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/mi-band-8-pro",
        },
    ],
    "keyboard": [
        {
            "title": "Keychron K2 V2 Mechanical Keyboard (TKL, Gateron Brown)",
            "price": 8499.0,
            "rating": 4.5,
            "review_count": 3200,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/KB001",
        },
        {
            "title": "Logitech MX Keys S Wireless Keyboard (Backlit)",
            "price": 9995.0,
            "rating": 4.4,
            "review_count": 2700,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/KB002",
        },
        {
            "title": "Cosmic Byte CB-GK-26 Firefly Mechanical Keyboard (Blue Switch)",
            "price": 2499.0,
            "rating": 4.0,
            "review_count": 9800,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/cosmic-byte-cb-gk-26",
        },
        {
            "title": "Zebronics Max Plus Mechanical Gaming Keyboard (RGB, Blue Switch)",
            "price": 1799.0,
            "rating": 3.9,
            "review_count": 6500,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/KB004",
        },
    ],
    "mouse": [
        {
            "title": "Logitech G502 X Wired Gaming Mouse (25600 DPI, HERO Sensor)",
            "price": 4995.0,
            "rating": 4.6,
            "review_count": 5100,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/MS001",
        },
        {
            "title": "Razer DeathAdder V3 Gaming Mouse (30000 DPI, Focus Pro Sensor)",
            "price": 7999.0,
            "rating": 4.5,
            "review_count": 2300,
            "source": "Flipkart",
            "link": "https://www.flipkart.com/razer-deathadder-v3",
        },
        {
            "title": "Portronics Toad 23 Wireless Mouse (2.4GHz, 1600 DPI)",
            "price": 699.0,
            "rating": 4.0,
            "review_count": 14200,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/MS003",
        },
        {
            "title": "Zebronics Zeb-Transformer-M Wired Gaming Mouse (RGB, 3200 DPI)",
            "price": 499.0,
            "rating": 3.8,
            "review_count": 11000,
            "source": "Amazon",
            "link": "https://www.amazon.in/dp/MS004",
        },
    ],
    "default": [
        {
            "title": "Sample Product A",
            "price": 5999.0,
            "rating": 4.2,
            "review_count": 1200,
            "source": "Amazon",
            "link": "#",
        },
        {
            "title": "Sample Product B",
            "price": 7499.0,
            "rating": 4.0,
            "review_count": 800,
            "source": "Flipkart",
            "link": "#",
        },
        {
            "title": "Sample Product C",
            "price": 4499.0,
            "rating": 4.4,
            "review_count": 2100,
            "source": "Amazon",
            "link": "#",
        },
    ],
}

# Keyword → category mapping. Checked in order; first match wins.
# Checked in order — first match wins.
# earbuds MUST come before headphones so "wireless earbuds" hits the right category.
CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "laptop":     ["laptop", "notebook", "macbook", "chromebook", "gaming laptop"],
    "earbuds":    ["earbud", "tws", "truly wireless", "in-ear", "iem",
                   "airpod", "galaxy buds", "neckband", "wireless earphone"],
    "headphones": ["headphone", "headset", "over-ear", "on-ear"],
    "phone":      ["phone", "mobile", "smartphone", "iphone", "android", "redmi",
                   "samsung", "oneplus", "realme", "poco", "vivo", "oppo"],
    "tv":         ["tv", "television", "smart tv", "oled", "qled", "monitor"],
    "tablet":     ["tablet", "ipad", "tab ", "kindle"],
    "speaker":    ["speaker", "bluetooth speaker", "soundbar", "home theatre"],
    "camera":     ["camera", "dslr", "mirrorless", "action cam", "gopro", "webcam"],
    "watch":      ["watch", "smartwatch", "fitness band", "fitbit", "mi band"],
    "keyboard":   ["keyboard", "mechanical keyboard"],
    "mouse":      ["mouse", "gaming mouse", "trackpad"],
}


def get_mock_products(query: str) -> list[dict]:
    """Return mock products for the best-matching category using keyword lookup."""
    q = query.lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        if any(kw in q for kw in keywords):
            return MOCK_PRODUCTS.get(category, MOCK_PRODUCTS["default"])
    return MOCK_PRODUCTS["default"]
